[2024-05-28T03:11:02.488+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_test_stage_data scheduled__2024-05-26T08:00:00+00:00 [queued]>
[2024-05-28T03:11:02.497+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_test_stage_data scheduled__2024-05-26T08:00:00+00:00 [queued]>
[2024-05-28T03:11:02.498+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T03:11:02.498+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-05-28T03:11:02.498+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T03:11:02.512+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_test_stage_data> on 2024-05-26 08:00:00+00:00
[2024-05-28T03:11:02.516+0000] {standard_task_runner.py:55} INFO - Started process 870 to run task
[2024-05-28T03:11:02.519+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_lookup_ingest', 'ti_test_stage_data', 'scheduled__2024-05-26T08:00:00+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmpqblaqcd8']
[2024-05-28T03:11:02.519+0000] {standard_task_runner.py:83} INFO - Job 279: Subtask ti_test_stage_data
[2024-05-28T03:11:02.572+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_lookup_ingest.ti_test_stage_data scheduled__2024-05-26T08:00:00+00:00 [running]> on host a64b6410e10e
[2024-05-28T03:11:02.637+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_lookup_ingest
AIRFLOW_CTX_TASK_ID=ti_test_stage_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T08:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-26T08:00:00+00:00
[2024-05-28T03:11:02.654+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-28T03:11:05.074+0000] {docker.py:354} INFO - [0m03:11:05  Running with dbt=1.5.11
[2024-05-28T03:11:05.185+0000] {docker.py:354} INFO - [0m03:11:05  Registered adapter: postgres=1.5.11
[2024-05-28T03:11:05.251+0000] {docker.py:354} INFO - [0m03:11:05  Found 6 models, 6 tests, 0 snapshots, 0 analyses, 422 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[2024-05-28T03:11:05.253+0000] {docker.py:354} INFO - [0m03:11:05
[2024-05-28T03:11:05.306+0000] {docker.py:354} INFO - [0m03:11:05  Concurrency: 4 threads (target='dev')
[2024-05-28T03:11:05.306+0000] {docker.py:354} INFO - [0m03:11:05
[2024-05-28T03:11:05.309+0000] {docker.py:354} INFO - [0m03:11:05  1 of 2 START test not_null_silver_unpivot_covid_geo_Country_Region ............. [RUN]
[2024-05-28T03:11:05.311+0000] {docker.py:354} INFO - [0m03:11:05  2 of 2 START test not_null_silver_unpivot_covid_geo_transf_province_state ...... [RUN]
[2024-05-28T03:11:10.078+0000] {docker.py:354} INFO - [0m03:11:10  2 of 2 PASS not_null_silver_unpivot_covid_geo_transf_province_state ............ [[32mPASS[0m in 4.75s]
[2024-05-28T03:11:10.855+0000] {docker.py:354} INFO - [0m03:11:10  1 of 2 PASS not_null_silver_unpivot_covid_geo_Country_Region ................... [[32mPASS[0m in 5.55s]
[2024-05-28T03:11:10.929+0000] {docker.py:354} INFO - [0m03:11:10
[2024-05-28T03:11:10.930+0000] {docker.py:354} INFO - [0m03:11:10  Finished running 2 tests in 0 hours 0 minutes and 5.68 seconds (5.68s).
[2024-05-28T03:11:10.941+0000] {docker.py:354} INFO - [0m03:11:10
[2024-05-28T03:11:10.941+0000] {docker.py:354} INFO - [0m03:11:10  [32mCompleted successfully[0m
[2024-05-28T03:11:10.941+0000] {docker.py:354} INFO - [0m03:11:10
[2024-05-28T03:11:10.941+0000] {docker.py:354} INFO - [0m03:11:10  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2024-05-28T03:11:11.696+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=franko_lookup_ingest, task_id=ti_test_stage_data, execution_date=20240526T080000, start_date=20240528T031102, end_date=20240528T031111
[2024-05-28T03:11:11.727+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-05-28T03:11:11.758+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
