[2024-05-27T20:55:59.710+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.ti_create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-27T20:55:59.723+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.ti_create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-27T20:55:59.723+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T20:55:59.723+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2024-05-27T20:55:59.724+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T20:55:59.741+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_create_seeds> on 2024-05-25 02:02:40.608195+00:00
[2024-05-27T20:55:59.748+0000] {standard_task_runner.py:55} INFO - Started process 4748 to run task
[2024-05-27T20:55:59.752+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_python', 'ti_create_seeds', 'manual__2024-05-25T02:02:40.608195+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmpcvwiv59a']
[2024-05-27T20:55:59.753+0000] {standard_task_runner.py:83} INFO - Job 80: Subtask ti_create_seeds
[2024-05-27T20:55:59.824+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_python.ti_create_seeds manual__2024-05-25T02:02:40.608195+00:00 [running]> on host a64b6410e10e
[2024-05-27T20:55:59.934+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_python
AIRFLOW_CTX_TASK_ID=ti_create_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:02:40.608195+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-25T02:02:40.608195+00:00
[2024-05-27T20:55:59.959+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-27T20:56:02.675+0000] {docker.py:354} INFO - [0m20:56:02  Running with dbt=1.5.11
[2024-05-27T20:56:02.861+0000] {docker.py:354} INFO - [0m20:56:02  Registered adapter: postgres=1.5.11
[2024-05-27T20:56:03.012+0000] {docker.py:354} INFO - [0m20:56:03  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 310 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics, 0 groups
[2024-05-27T20:56:03.015+0000] {docker.py:354} INFO - [0m20:56:03
[2024-05-27T20:56:03.103+0000] {docker.py:354} INFO - [0m20:56:03  Concurrency: 4 threads (target='dev')
[2024-05-27T20:56:03.103+0000] {docker.py:354} INFO - [0m20:56:03
[2024-05-27T20:56:03.107+0000] {docker.py:354} INFO - [0m20:56:03  1 of 1 START seed file dev.time_series_covid19_confirmed_global ................ [RUN]
[2024-05-27T20:57:23.194+0000] {docker.py:354} INFO - [0m20:57:23  1 of 1 OK loaded seed file dev.time_series_covid19_confirmed_global ............ [[32mINSERT 289[0m in 80.09s]
[2024-05-27T20:57:23.244+0000] {docker.py:354} INFO - [0m20:57:23
[2024-05-27T20:57:23.244+0000] {docker.py:354} INFO - [0m20:57:23  Finished running 1 seed in 0 hours 1 minutes and 20.23 seconds (80.23s).
[2024-05-27T20:57:23.258+0000] {docker.py:354} INFO - [0m20:57:23
[2024-05-27T20:57:23.259+0000] {docker.py:354} INFO - [0m20:57:23  [32mCompleted successfully[0m
[2024-05-27T20:57:23.260+0000] {docker.py:354} INFO - [0m20:57:23
[2024-05-27T20:57:23.261+0000] {docker.py:354} INFO - [0m20:57:23  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-05-27T20:57:24.586+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=franko_python, task_id=ti_create_seeds, execution_date=20240525T020240, start_date=20240527T205559, end_date=20240527T205724
[2024-05-27T20:57:24.641+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-05-27T20:57:24.670+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
