[2024-05-27T23:25:57.142+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_load_raw_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-27T23:25:57.154+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_load_raw_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-27T23:25:57.154+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T23:25:57.154+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 5
[2024-05-27T23:25:57.154+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T23:25:57.172+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_load_raw_data> on 2024-05-27 21:49:08.726117+00:00
[2024-05-27T23:25:57.179+0000] {standard_task_runner.py:55} INFO - Started process 16766 to run task
[2024-05-27T23:25:57.182+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_lookup_ingest', 'ti_load_raw_data', 'manual__2024-05-27T21:49:08.726117+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmprb3lh09g']
[2024-05-27T23:25:57.183+0000] {standard_task_runner.py:83} INFO - Job 106: Subtask ti_load_raw_data
[2024-05-27T23:25:57.246+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_lookup_ingest.ti_load_raw_data manual__2024-05-27T21:49:08.726117+00:00 [running]> on host a64b6410e10e
[2024-05-27T23:25:57.320+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_lookup_ingest
AIRFLOW_CTX_TASK_ID=ti_load_raw_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-27T21:49:08.726117+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-27T21:49:08.726117+00:00
[2024-05-27T23:25:57.340+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-27T23:25:59.338+0000] {docker.py:354} INFO - [0m23:25:59  Running with dbt=1.5.11
[2024-05-27T23:25:59.457+0000] {docker.py:354} INFO - [0m23:25:59  Registered adapter: postgres=1.5.11
[2024-05-27T23:25:59.534+0000] {docker.py:354} INFO - [0m23:25:59  Found 4 models, 4 tests, 0 snapshots, 0 analyses, 422 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[2024-05-27T23:25:59.535+0000] {docker.py:354} INFO - [0m23:25:59
[2024-05-27T23:25:59.600+0000] {docker.py:354} INFO - [0m23:25:59  Concurrency: 4 threads (target='dev')
[2024-05-27T23:25:59.600+0000] {docker.py:354} INFO - [0m23:25:59
[2024-05-27T23:25:59.603+0000] {docker.py:354} INFO - [0m23:25:59  1 of 1 START seed file dev.time_series_covid19_confirmed_global ................ [RUN]
[2024-05-27T23:27:15.552+0000] {docker.py:354} INFO - [0m23:27:15  1 of 1 OK loaded seed file dev.time_series_covid19_confirmed_global ............ [[32mINSERT 289[0m in 75.95s]
[2024-05-27T23:27:15.631+0000] {docker.py:354} INFO - [0m23:27:15
[2024-05-27T23:27:15.631+0000] {docker.py:354} INFO - [0m23:27:15  Finished running 1 seed in 0 hours 1 minutes and 16.09 seconds (76.09s).
[2024-05-27T23:27:15.645+0000] {docker.py:354} INFO - [0m23:27:15
[2024-05-27T23:27:15.646+0000] {docker.py:354} INFO - [0m23:27:15  [32mCompleted successfully[0m
[2024-05-27T23:27:15.647+0000] {docker.py:354} INFO - [0m23:27:15
[2024-05-27T23:27:15.647+0000] {docker.py:354} INFO - [0m23:27:15  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-05-27T23:27:16.999+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=franko_lookup_ingest, task_id=ti_load_raw_data, execution_date=20240527T214908, start_date=20240527T232557, end_date=20240527T232716
[2024-05-27T23:27:17.044+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-05-27T23:27:17.092+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
