[2024-05-28T03:01:44.554+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_load_raw_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-28T03:01:44.566+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_load_raw_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-28T03:01:44.566+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T03:01:44.566+0000] {taskinstance.py:1284} INFO - Starting attempt 6 of 6
[2024-05-28T03:01:44.566+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T03:01:44.583+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_load_raw_data> on 2024-05-27 21:49:08.726117+00:00
[2024-05-28T03:01:44.588+0000] {standard_task_runner.py:55} INFO - Started process 153 to run task
[2024-05-28T03:01:44.592+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_lookup_ingest', 'ti_load_raw_data', 'manual__2024-05-27T21:49:08.726117+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmp6uzk6v4y']
[2024-05-28T03:01:44.592+0000] {standard_task_runner.py:83} INFO - Job 272: Subtask ti_load_raw_data
[2024-05-28T03:01:44.662+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_lookup_ingest.ti_load_raw_data manual__2024-05-27T21:49:08.726117+00:00 [running]> on host a64b6410e10e
[2024-05-28T03:01:44.789+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_lookup_ingest
AIRFLOW_CTX_TASK_ID=ti_load_raw_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-27T21:49:08.726117+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-27T21:49:08.726117+00:00
[2024-05-28T03:01:44.822+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-28T03:01:48.395+0000] {docker.py:354} INFO - [0m03:01:48  Running with dbt=1.5.11
[2024-05-28T03:01:48.760+0000] {docker.py:354} INFO - [0m03:01:48  Registered adapter: postgres=1.5.11
[2024-05-28T03:01:48.968+0000] {docker.py:354} INFO - [0m03:01:48  Found 6 models, 6 tests, 0 snapshots, 0 analyses, 422 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[2024-05-28T03:01:48.971+0000] {docker.py:354} INFO - [0m03:01:48
[2024-05-28T03:01:49.091+0000] {docker.py:354} INFO - [0m03:01:49  Concurrency: 4 threads (target='dev')
[2024-05-28T03:01:49.092+0000] {docker.py:354} INFO - [0m03:01:49
[2024-05-28T03:01:49.096+0000] {docker.py:354} INFO - [0m03:01:49  1 of 1 START seed file dev.time_series_covid19_confirmed_global ................ [RUN]
[2024-05-28T03:03:01.792+0000] {docker.py:354} INFO - [0m03:03:01  1 of 1 OK loaded seed file dev.time_series_covid19_confirmed_global ............ [[32mINSERT 289[0m in 72.70s]
[2024-05-28T03:03:01.882+0000] {docker.py:354} INFO - [0m03:03:01
[2024-05-28T03:03:01.883+0000] {docker.py:354} INFO - [0m03:03:01  Finished running 1 seed in 0 hours 1 minutes and 12.91 seconds (72.91s).
[2024-05-28T03:03:01.892+0000] {docker.py:354} INFO - [0m03:03:01
[2024-05-28T03:03:01.893+0000] {docker.py:354} INFO - [0m03:03:01  [32mCompleted successfully[0m
[2024-05-28T03:03:01.893+0000] {docker.py:354} INFO - [0m03:03:01
[2024-05-28T03:03:01.893+0000] {docker.py:354} INFO - [0m03:03:01  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-05-28T03:03:03.233+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=franko_lookup_ingest, task_id=ti_load_raw_data, execution_date=20240527T214908, start_date=20240528T030144, end_date=20240528T030303
[2024-05-28T03:03:03.274+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-05-28T03:03:03.313+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
