[2024-05-28T03:18:18.516+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_docs_generate scheduled__2024-05-26T08:00:00+00:00 [queued]>
[2024-05-28T03:18:18.528+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_docs_generate scheduled__2024-05-26T08:00:00+00:00 [queued]>
[2024-05-28T03:18:18.529+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T03:18:18.529+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2024-05-28T03:18:18.529+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T03:18:18.547+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_docs_generate> on 2024-05-26 08:00:00+00:00
[2024-05-28T03:18:18.553+0000] {standard_task_runner.py:55} INFO - Started process 1442 to run task
[2024-05-28T03:18:18.557+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_lookup_ingest', 'ti_docs_generate', 'scheduled__2024-05-26T08:00:00+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmpj3fzxwih']
[2024-05-28T03:18:18.557+0000] {standard_task_runner.py:83} INFO - Job 283: Subtask ti_docs_generate
[2024-05-28T03:18:18.624+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_lookup_ingest.ti_docs_generate scheduled__2024-05-26T08:00:00+00:00 [running]> on host a64b6410e10e
[2024-05-28T03:18:18.729+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_lookup_ingest
AIRFLOW_CTX_TASK_ID=ti_docs_generate
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T08:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-26T08:00:00+00:00
[2024-05-28T03:18:18.753+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-28T03:18:21.457+0000] {docker.py:354} INFO - [0m03:18:21  Running with dbt=1.5.11
[2024-05-28T03:18:21.638+0000] {docker.py:354} INFO - [0m03:18:21  Registered adapter: postgres=1.5.11
[2024-05-28T03:18:21.743+0000] {docker.py:354} INFO - [0m03:18:21  Building catalog
[2024-05-28T03:18:22.291+0000] {docker.py:354} INFO - [0m03:18:22  Catalog written to /usr/app/projects/franko/target/catalog.json
[2024-05-28T03:18:23.350+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=franko_lookup_ingest, task_id=ti_docs_generate, execution_date=20240526T080000, start_date=20240528T031818, end_date=20240528T031823
[2024-05-28T03:18:23.389+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-05-28T03:18:23.432+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
